volumes:
  postgres-data:

x-database-environment: &postgres-env
  POSTGRES_DB: ${POSTGRES_DB:-testdb}
  POSTGRES_USER: ${POSTGRES_USER:-testuser}
  POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-testpassword}

services:
  postgres-db:
    image: postgres:13.15-alpine
    restart: unless-stopped
    environment:
      <<: *postgres-env
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      retries: 3
      interval: 3s
      timeout: 3s
      start_period: 10s
    expose:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data

  discovery-service:
    image: demo-discovery-service
    depends_on:
      - postgres-db
    ports:
      - "8761:8761"

  gateway-service:
    image: demo-gateway-service
    environment:
      SPRING_EUREKA_DEFAULT_ZONE: discovery-service
      SPRING_SERVER_PORT: 8080
    ports:
      - "80:8080"
    depends_on:
      - discovery-service

  driver-service:
    image: demo-driver-service
    environment:
      <<: *postgres-env
      POSTGRES_HOST: postgres-db
      POSTGRES_PORT: 5432
      SPRING_EUREKA_DEFAULT_ZONE: discovery-service
    depends_on:
      - discovery-service

  team-service:
    image: demo-team-service
    environment:
      <<: *postgres-env
      POSTGRES_HOST: postgres-db
      POSTGRES_PORT: 5432
      SPRING_EUREKA_DEFAULT_ZONE: discovery-service
    depends_on:
      - discovery-service

  race-service:
    image: demo-race-service
    environment:
      <<: *postgres-env
      POSTGRES_HOST: postgres-db
      POSTGRES_PORT: 5432
      SPRING_EUREKA_DEFAULT_ZONE: discovery-service
    depends_on:
      - discovery-service
