spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allow-credentials: true
            allowed-methods: '*'
            allowed-headers: '*'
            allowed-origin-patterns: '*'
      discovery:
        locator:
          enabled: true
      routes:
        - id: driver-service
          uri: lb://driver-service
          predicates:
            - Path=/api/drivers/**
          filters:
            - StripPrefix=2
        - id: team-service
          uri: lb://team-service
          predicates:
            - Path=/api/teams/**
          filters:
            - StripPrefix=2
        - id: race-service
          uri: lb://race-service
          predicates:
            - Path=/api/races/**
          filters:
            - StripPrefix=2
server:
  port: ${SPRING_SERVER_PORT:8080}
  address: 0.0.0.0

eureka:
  client:
    service-url:
      defaultZone: http://${SPRING_EUREKA_DEFAULT_ZONE:localhost}:8761/eureka/
